spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    password:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/view/

flyway:
  user: root
  password:
  schemas: supplier_portal
  url: jdbc:mysql://localhost:3306/
  locations: filesystem:db/migration

db:
  default-schema: supplier_portal

test:
  value: 4